import React from "react";
import Link from "next/link";
import { ArrowLeft, FileCheck, Scale, AlertTriangle, Cpu, Mail } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Terms and Conditions governing the use of NOVA Voice Agent software and interfaces.",
};

export default function TermsAndConditionsPage() {
  const lastUpdated = "September 21, 2026";

  return (
    <div className="min-h-screen bg-[#F6F7F9] text-[#2B1810] font-serif py-12 px-6 sm:px-10 max-w-4xl mx-auto">
      {/* Back button */}
      <div className="mb-8">
        <Link
          href="/"
          className="inline-flex items-center space-x-2 text-xs font-sans text-[#6B4E3D] hover:text-[#2B1810] transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to NOVA Voice Agent</span>
        </Link>
      </div>

      {/* Header */}
      <header className="border-b border-[#2B1810]/15 pb-6 mb-8">
        <div className="flex items-center space-x-3 mb-3">
          <div className="w-9 h-9 rounded-xl bg-[#2B1810]/8 border border-[#2B1810]/15 flex items-center justify-center text-[#2B1810]">
            <Scale className="w-5 h-5 text-[#8C6552]" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-[#2B1810]">
            Terms and Conditions
          </h1>
        </div>
        <p className="text-xs text-[#6B4E3D] font-sans">
          Last Updated: {lastUpdated} &bull; Service: NOVA Voice Agent Platform
        </p>
      </header>

      {/* Content */}
      <div className="space-y-8 text-sm text-[#45281C] leading-relaxed">
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">01.</span>
            <span>Agreement to Terms</span>
          </h2>
          <p>
            By accessing or using the NOVA application (&quot;the Application&quot;, &quot;the Service&quot;), you agree to be bound by these Terms and Conditions. If you do not agree, do not access or use the Service.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">02.</span>
            <span>Permitted Use & System Functionality</span>
          </h2>
          <p>
            NOVA is a multimodal AI agent designed for interactive voice conversations, document knowledge retrieval (RAG), conversational memory, and tool execution (e.g. calculation, weather, search).
          </p>
          <p>
            You agree to use the Service in compliance with all applicable local, national, and international laws. You agree not to:
          </p>
          <ul className="list-disc list-inside space-y-1 pl-2 text-[#45281C]">
            <li>Interfere with, compromise, or disrupt WebSocket connections or server integrity.</li>
            <li>Upload documents containing malicious code, viruses, or illegal material.</li>
            <li>Use the system to generate unlawful, harassing, defamatory, or harmful content.</li>
            <li>Attempt unauthorized access to underlying server environments or other user databases.</li>
          </ul>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">03.</span>
            <span>AI Provider Responses & Accuracy Disclaimer</span>
          </h2>
          <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 text-xs space-y-1.5 shadow-xs">
            <div className="flex items-center space-x-2 font-semibold text-amber-950">
              <AlertTriangle className="w-4 h-4 text-amber-700 shrink-0" />
              <span>Experimental AI Technology Notice</span>
            </div>
            <p className="text-amber-800 leading-relaxed font-serif">
              Responses generated by NOVA are powered by Large Language Models and speech models. Artificial intelligence can produce inaccurate, incomplete, or hallucinated statements. NOVA should not be used as the sole basis for critical medical, legal, financial, or safety-critical decisions.
            </p>
          </div>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">04.</span>
            <span>Intellectual Property & User Content</span>
          </h2>
          <p>
            The software, user interface design, branding, and original source code of NOVA are protected by copyright and intellectual property laws.
          </p>
          <p>
            You retain all ownership rights to any documents, text, or files you upload to the Application. By uploading materials, you grant NOVA only the limited right to process and index the content strictly for the purpose of answering your queries.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">05.</span>
            <span>Limitation of Liability</span>
          </h2>
          <p>
            To the maximum extent permitted by applicable law, NOVA and its contributors shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, goodwill, or operational disruption arising from the use or inability to use the Application.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <span className="text-[#8C6552] font-sans text-xs">06.</span>
            <span>Changes to Terms</span>
          </h2>
          <p>
            We reserve the right to update these terms to reflect technical improvements or legal requirements. Material updates will be indicated by the &quot;Last Updated&quot; date at the top of this document.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-3 border-t border-[#2B1810]/15 pt-6">
          <h2 className="text-base font-semibold text-[#2B1810] flex items-center space-x-2">
            <Mail className="w-4 h-4 text-[#8C6552]" />
            <span>Contact Information</span>
          </h2>
          <p>
            If you have any questions or require clarification regarding these Terms and Conditions:
          </p>
          <div className="p-4 rounded-xl bg-white border border-[#2B1810]/12 text-xs font-sans space-y-1 text-[#45281C] shadow-xs">
            <div><strong>Entity:</strong> NOVA Voice Agent Platform</div>
            <div><strong>Email:</strong> chitrashrees897@gmail.com</div>
            <div><strong>Repository:</strong> <a href="https://github.com/chitrashrees897-Chitra/chatbot_chitra" target="_blank" rel="noopener noreferrer" className="text-[#2B1810] underline">github.com/chitrashrees897-Chitra/chatbot_chitra</a></div>
          </div>
        </section>
      </div>

      {/* Footer link back */}
      <footer className="mt-12 pt-6 border-t border-[#2B1810]/15 flex justify-between text-xs text-[#8C6552]">
        <div>&copy; {new Date().getFullYear()} NOVA. All rights reserved.</div>
        <div className="space-x-4">
          <Link href="/privacy-policy" className="hover:text-[#2B1810] transition-colors">
            Privacy Policy
          </Link>
          <Link href="/" className="hover:text-[#2B1810] transition-colors">
            App Home
          </Link>
        </div>
      </footer>
    </div>
  );
}
